name: auto_inc_version
on:
  pull_request:
    branches:
        - 'dev'
        - 'release'
    types:
      - opened
      - closed
      - edited
      - synchronize

jobs:
  autoInc:
    name: Run auto increment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: increment version
        run: ./gradlew autoInc
        if: github.event.pull_request.merged == 'true'
