name: Build_release_signed_artifacts

on:
  workflow_dispatch:

env:
  SIGNING_STORE_PASSWORD_RELEASE: ${{ secrets.SIGNING_STORE_PASSWORD_RELEASE }}
  SIGNING_KEY_ALIAS_RELEASE: ${{ secrets.SIGNING_KEY_ALIAS_RELEASE }}
  SIGNING_KEY_PASSWORD_RELEASE: ${{ secrets.SIGNING_KEY_PASSWORD_RELEASE }}
  SIGNING_STORE_FILE_PATH_RELEASE: ${{ secrets.SIGNING_STORE_FILE_PATH_RELEASE }}

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: build release artifacts
        run: |
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab